### ISSUE TITLE
 Gold Dust Item conflict  

### ISSUE THREAD

**Issue by TheDWPCer** [freethemice/sensibletoolbox#5] opened 2017-03-26 07:04 UTC
So there is alot of items that are in Slimefun but STB does has some of the same items but they don't work together
There is a way to get all of them
But if this is intended
Just close the issue
Btw this is very minor

**Comment by freethemice** [comment] 2017-03-26 21:51
this is a duplicate of #1

**Closed by freethemice** 2017-03-26 21:51 UTC
Labels: duplicate
